apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "32108"
    prometheus.io/scrape: "true"
  labels:
    component: kube-controller-manager
    tier: control-plane
  name: kube-controller
  namespace: kube-system
spec:
  clusterIP:
  ports:
  - name: metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
    nodePort: 32108
  selector:
    component: kube-controller-manager
    tier: control-plane
  type: NodePort
