apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "32107"
    prometheus.io/scrape: "true"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  clusterIP:
  ports:
  - name: metrics
    port: 10251
    protocol: TCP
    targetPort: 10251
    nodePort: 32107
  selector:
    component: kube-scheduler
    tier: control-plane
  type: NodePort
